//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissileSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MissileSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to command is empty.
        /// </summary>
        internal static string CommandEmpty {
            get {
                return ResourceManager.GetString("CommandEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to command must be one of the following: up, down, left, right, reset, fire.
        /// </summary>
        internal static string CommandMustBeOneOfFollowing {
            get {
                return ResourceManager.GetString("CommandMustBeOneOfFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to command set name is empty.
        /// </summary>
        internal static string CommandSetNameEmpty {
            get {
                return ResourceManager.GetString("CommandSetNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device is not ready, please check the connection!.
        /// </summary>
        internal static string DeviceIsNotReady {
            get {
                return ResourceManager.GetString("DeviceIsNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;device&quot; parameter is null!.
        /// </summary>
        internal static string DeviceIsNull {
            get {
                return ResourceManager.GetString("DeviceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first line in the config must be a command set name. There can be no commands before the first command set name!.
        /// </summary>
        internal static string FirstLineMustBeCommandSetName {
            get {
                return ResourceManager.GetString("FirstLineMustBeCommandSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;launcher&quot; parameter is null!.
        /// </summary>
        internal static string LauncherIsNull {
            get {
                return ResourceManager.GetString("LauncherIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher model &apos;{0}&apos; does not implement interface ILauncherModel.
        /// </summary>
        internal static string LauncherModelIsNotILauncherModel {
            get {
                return ResourceManager.GetString("LauncherModelIsNotILauncherModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No launcher model with this name available: .
        /// </summary>
        internal static string LauncherModelNotFound {
            get {
                return ResourceManager.GetString("LauncherModelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This line in the config file does not contain exactly two items: .
        /// </summary>
        internal static string LineDoesNotContainTwoItems {
            get {
                return ResourceManager.GetString("LineDoesNotContainTwoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No command sets available. You need to load them first using the LoadCommandSets method!.
        /// </summary>
        internal static string NoCommandSets {
            get {
                return ResourceManager.GetString("NoCommandSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second item in this line in the config file must be numeric: .
        /// </summary>
        internal static string SecondItemMustBeNumeric {
            get {
                return ResourceManager.GetString("SecondItemMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value must be equal or greater than zero.
        /// </summary>
        internal static string ValueMustBeEqualGreaterZero {
            get {
                return ResourceManager.GetString("ValueMustBeEqualGreaterZero", resourceCulture);
            }
        }
    }
}
